# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c9747f622a8248a497a159f633da0417325457a9a931d45a1f68b9141c4e3afb47fdc5b71d5e3152359eb7969a08d51e698a2b4b0814e2698b4899b615bc74d

test:
  secret_key_base: ddc7093a602e5dc5cacea3a06e1b57ba5c3b9da0f7eefd221e266888d2c01c16eecd742e9003194d697198b0832904a75fe0e061f397646022424d813ef5e1dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
